// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TontineDbContext))]
    [Migration("20260410003830_SyncModelSnapshot")]
    partial class SyncModelSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.BillingManagement.Abonnement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("devise");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_debut");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_fin");

                    b.Property<DateTime?>("DateFinGrace")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_fin_grace");

                    b.Property<string>("DernierTransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("dernier_transaction_id");

                    b.Property<string>("GestionnaireId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("gestionnaire_id");

                    b.Property<decimal>("MontantMensuel")
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("montant_mensuel");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("plan");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<bool>("RenouvellementAuto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("renouvellement_auto");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("statut");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DateFin")
                        .HasDatabaseName("ix_abonnements_date_fin");

                    b.HasIndex("GestionnaireId")
                        .HasDatabaseName("ix_abonnements_gestionnaire");

                    b.HasIndex("PlanId");

                    b.HasIndex("Statut")
                        .HasDatabaseName("ix_abonnements_statut");

                    b.ToTable("abonnements", (string)null);
                });

            modelBuilder.Entity("Domain.BillingManagement.PlanAbonnement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Devise")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("devise");

                    b.Property<bool>("EstActif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("est_actif");

                    b.Property<int>("MaxMembresParTontine")
                        .HasColumnType("integer")
                        .HasColumnName("max_membres_par_tontine");

                    b.Property<int>("MaxTontines")
                        .HasColumnType("integer")
                        .HasColumnName("max_tontines");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nom");

                    b.Property<decimal>("PrixMensuel")
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("prix_mensuel");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_plans_abonnement_code");

                    b.ToTable("plans_abonnement", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Code = "GRATUIT",
                            Description = "Plan gratuit : 1 tontine, 10 membres max",
                            Devise = "XOF",
                            EstActif = true,
                            MaxMembresParTontine = 10,
                            MaxTontines = 1,
                            Nom = "Gratuit",
                            PrixMensuel = 0m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Code = "PRO",
                            Description = "Plan Pro : 10 tontines, membres illimités - 2000 FCFA/mois",
                            Devise = "XOF",
                            EstActif = true,
                            MaxMembresParTontine = 2147483647,
                            MaxTontines = 10,
                            Nom = "Pro",
                            PrixMensuel = 2000m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Code = "IMF",
                            Description = "Plan IMF : sur devis, tontines et membres illimités",
                            Devise = "XOF",
                            EstActif = true,
                            MaxMembresParTontine = 2147483647,
                            MaxTontines = 2147483647,
                            Nom = "IMF",
                            PrixMensuel = 0m
                        });
                });

            modelBuilder.Entity("Domain.Common.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("contenu");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Erreur")
                        .HasColumnType("text")
                        .HasColumnName("erreur");

                    b.Property<int>("NombreTentatives")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("nombre_tentatives");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("TypeEvenement")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type_evenement");

                    b.HasKey("Id");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Domain.CreditScoringManagement.ProfilCredit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("DonneesInsuffisantes")
                        .HasColumnType("boolean")
                        .HasColumnName("donnees_insuffisantes");

                    b.Property<Guid>("MembreId")
                        .HasColumnType("uuid")
                        .HasColumnName("membre_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MembreId")
                        .IsUnique()
                        .HasDatabaseName("uq_profils_credit_membre");

                    b.ToTable("profils_credit", (string)null);
                });

            modelBuilder.Entity("Domain.IdentityManagement.Utilisateur", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("EstActif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("est_actif");

                    b.Property<string>("FcmToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("fcm_token");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("mot_de_passe_hash");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<bool>("SmsOptOut")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("sms_opt_out");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telephone");

                    b.HasKey("Id");

                    b.HasIndex("Telephone")
                        .IsUnique();

                    b.ToTable("utilisateurs", (string)null);
                });

            modelBuilder.Entity("Domain.NotificationManagement.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("canal");

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contenu");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DateEnvoi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_envoi");

                    b.Property<string>("DestinataireId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destinataire_id");

                    b.Property<int>("MaxTentatives")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("max_tentatives");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("statut");

                    b.Property<int>("TentativesEnvoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("tentatives_envoi");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Domain.PaymentManagement.Entities.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActeurId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("acteur_id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<string>("HashCourant")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash_courant");

                    b.Property<string>("HashPrecedent")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash_precedent");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("horodatage");

                    b.Property<Guid>("TontineId")
                        .HasColumnType("uuid")
                        .HasColumnName("tontine_id");

                    b.Property<Guid>("VersementId")
                        .HasColumnType("uuid")
                        .HasColumnName("versement_id");

                    b.HasKey("Id");

                    b.HasIndex("ActeurId")
                        .HasDatabaseName("ix_audit_entries_acteur");

                    b.HasIndex("Action")
                        .HasDatabaseName("ix_audit_entries_action");

                    b.HasIndex("VersementId");

                    b.HasIndex("TontineId", "Timestamp")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_entries_tontine_horodatage");

                    b.ToTable("audit_entries", (string)null);
                });

            modelBuilder.Entity("Domain.PaymentManagement.Versement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HashCourant")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash_courant");

                    b.Property<string>("HashPrecedent")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash_precedent");

                    b.Property<Guid>("PayeurId")
                        .HasColumnType("uuid")
                        .HasColumnName("membre_id");

                    b.Property<string>("ReferenceExterne")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_externe");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("statut");

                    b.Property<Guid>("TontineId")
                        .HasColumnType("uuid")
                        .HasColumnName("tontine_id");

                    b.Property<Guid>("TourId")
                        .HasColumnType("uuid")
                        .HasColumnName("tour_id");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceExterne")
                        .IsUnique()
                        .HasDatabaseName("uq_versements_reference_externe")
                        .HasFilter("reference_externe IS NOT NULL");

                    b.HasIndex("TontineId", "TourId")
                        .HasDatabaseName("ix_versements_tontine_tour");

                    b.ToTable("versements", (string)null);
                });

            modelBuilder.Entity("Domain.TontineManagement.Entities.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code_hash");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_expiration");

                    b.Property<int>("NombreUsagesActuels")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("nombre_usages_actuels");

                    b.Property<int>("NombreUsagesMax")
                        .HasColumnType("integer")
                        .HasColumnName("nombre_usages_max");

                    b.Property<Guid?>("tontine_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CodeHash")
                        .HasDatabaseName("ix_codes_invitation_code_hash");

                    b.HasIndex("tontine_id");

                    b.ToTable("codes_invitation", (string)null);
                });

            modelBuilder.Entity("Domain.TontineManagement.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom");

                    b.Property<int>("Rang")
                        .HasColumnType("integer")
                        .HasColumnName("rang");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("statut");

                    b.Property<Guid?>("UtilisateurId")
                        .HasColumnType("uuid")
                        .HasColumnName("utilisateur_id");

                    b.Property<Guid?>("tontine_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("tontine_id");

                    b.ToTable("membres_tontine", (string)null);
                });

            modelBuilder.Entity("Domain.TontineManagement.Entities.Round", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BeneficiaryId")
                        .HasColumnType("uuid")
                        .HasColumnName("beneficiaire_id");

                    b.Property<DateTime>("DateLimite")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_limite");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("est_complete");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer")
                        .HasColumnName("numero_tour");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_prevue");

                    b.Property<Guid?>("tontine_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("tontine_id");

                    b.ToTable("tours_de_role", (string)null);
                });

            modelBuilder.Entity("Domain.TontineManagement.Tontine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("GestionnaireId")
                        .HasColumnType("uuid")
                        .HasColumnName("gestionnaire_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("statut");

                    b.HasKey("Id");

                    b.ToTable("tontines", (string)null);
                });

            modelBuilder.Entity("Domain.BillingManagement.Abonnement", b =>
                {
                    b.HasOne("Domain.BillingManagement.PlanAbonnement", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.CreditScoringManagement.ProfilCredit", b =>
                {
                    b.OwnsOne("Domain.CreditScoringManagement.Entities.HistoriqueComportement", "Historique", b1 =>
                        {
                            b1.Property<Guid>("ProfilCreditId")
                                .HasColumnType("uuid");

                            b1.Property<int>("CyclesCompletes")
                                .HasColumnType("integer")
                                .HasColumnName("historique_cycles_completes");

                            b1.Property<DateTime>("DatePremierVersement")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("historique_date_premier_versement");

                            b1.Property<DateTime>("DernierVersement")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("historique_dernier_versement");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("historique_id");

                            b1.Property<int>("TotalVersements")
                                .HasColumnType("integer")
                                .HasColumnName("historique_total_versements");

                            b1.Property<int>("VersementsPonctuels")
                                .HasColumnType("integer")
                                .HasColumnName("historique_versements_ponctuels");

                            b1.HasKey("ProfilCreditId");

                            b1.ToTable("profils_credit");

                            b1.WithOwner()
                                .HasForeignKey("ProfilCreditId");
                        });

                    b.OwnsOne("Domain.CreditScoringManagement.ValueObjects.ScoreCalcule", "ScoreActuel", b1 =>
                        {
                            b1.Property<Guid>("ProfilCreditId")
                                .HasColumnType("uuid");

                            b1.Property<int>("AncienneteEnMois")
                                .HasColumnType("integer")
                                .HasColumnName("score_anciennete_mois");

                            b1.Property<DateTime>("CalculeLe")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("score_calcule_le");

                            b1.Property<int>("CyclesCompletes")
                                .HasColumnType("integer")
                                .HasColumnName("score_cycles_completes");

                            b1.Property<string>("Niveau")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("score_niveau");

                            b1.Property<double>("TauxPonctualite")
                                .HasColumnType("double precision")
                                .HasColumnName("score_taux_ponctualite");

                            b1.Property<int>("Valeur")
                                .HasColumnType("integer")
                                .HasColumnName("score_valeur");

                            b1.HasKey("ProfilCreditId");

                            b1.ToTable("profils_credit");

                            b1.WithOwner()
                                .HasForeignKey("ProfilCreditId");
                        });

                    b.Navigation("Historique")
                        .IsRequired();

                    b.Navigation("ScoreActuel")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.NotificationManagement.Notification", b =>
                {
                    b.OwnsOne("Domain.NotificationManagement.ValueObjects.ContenuMessage", "ContenuMessage", b1 =>
                        {
                            b1.Property<Guid>("NotificationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Texte")
                                .IsRequired()
                                .HasMaxLength(160)
                                .HasColumnType("character varying(160)")
                                .HasColumnName("contenu_message");

                            b1.HasKey("NotificationId");

                            b1.ToTable("notifications");

                            b1.WithOwner()
                                .HasForeignKey("NotificationId");
                        });

                    b.Navigation("ContenuMessage")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.PaymentManagement.Entities.AuditEntry", b =>
                {
                    b.HasOne("Domain.PaymentManagement.Versement", null)
                        .WithMany("AuditTrail")
                        .HasForeignKey("VersementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.PaymentManagement.Versement", b =>
                {
                    b.OwnsOne("Domain.PaymentManagement.ValueObjects.Montant", "Montant", b1 =>
                        {
                            b1.Property<Guid>("VersementId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Devise")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("devise");

                            b1.Property<decimal>("Valeur")
                                .HasColumnType("numeric(15,2)")
                                .HasColumnName("montant");

                            b1.HasKey("VersementId");

                            b1.ToTable("versements");

                            b1.WithOwner()
                                .HasForeignKey("VersementId");
                        });

                    b.Navigation("Montant")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.TontineManagement.Entities.Invitation", b =>
                {
                    b.HasOne("Domain.TontineManagement.Tontine", null)
                        .WithMany("Invitations")
                        .HasForeignKey("tontine_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain.TontineManagement.Entities.Member", b =>
                {
                    b.HasOne("Domain.TontineManagement.Tontine", null)
                        .WithMany("Members")
                        .HasForeignKey("tontine_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain.TontineManagement.Entities.Round", b =>
                {
                    b.HasOne("Domain.TontineManagement.Tontine", null)
                        .WithMany("Rounds")
                        .HasForeignKey("tontine_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain.TontineManagement.Tontine", b =>
                {
                    b.OwnsOne("Domain.TontineManagement.ValueObjects.Reglement", "Reglement", b1 =>
                        {
                            b1.Property<Guid>("TontineId")
                                .HasColumnType("uuid");

                            b1.Property<int>("MaxMembers")
                                .HasColumnType("integer")
                                .HasColumnName("max_membres");

                            b1.Property<int>("MinMembresActivation")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(3)
                                .HasColumnName("min_membres_activation");

                            b1.Property<string>("ModeAttribution")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("mode_attribution");

                            b1.Property<string>("Periodicity")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("periodicite");

                            b1.HasKey("TontineId");

                            b1.ToTable("tontines");

                            b1.WithOwner()
                                .HasForeignKey("TontineId");

                            b1.OwnsOne("Domain.TontineManagement.ValueObjects.ContributionAmount", "ContributionAmount", b2 =>
                                {
                                    b2.Property<Guid>("ReglementTontineId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric(15,2)")
                                        .HasColumnName("montant_cotisation");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("devise");

                                    b2.HasKey("ReglementTontineId");

                                    b2.ToTable("tontines");

                                    b2.WithOwner()
                                        .HasForeignKey("ReglementTontineId");
                                });

                            b1.Navigation("ContributionAmount")
                                .IsRequired();
                        });

                    b.Navigation("Reglement")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.PaymentManagement.Versement", b =>
                {
                    b.Navigation("AuditTrail");
                });

            modelBuilder.Entity("Domain.TontineManagement.Tontine", b =>
                {
                    b.Navigation("Invitations");

                    b.Navigation("Members");

                    b.Navigation("Rounds");
                });
#pragma warning restore 612, 618
        }
    }
}
